import { PRIMARY_APP_COLOR, SECONDARY_APP_COLOR } from './styleConstants';
import { CAR_CLASSES_OBJ, CURRENCY_EXCH_UAH_IN_USD, METERS_IN_KM } from './taxiPrices';
import { AMOUNT_LETTERS_OF_ADDRESS, KYIV_POSITION } from './tripsData';

export {
  PRIMARY_APP_COLOR,
  SECONDARY_APP_COLOR,
  METERS_IN_KM,
  CURRENCY_EXCH_UAH_IN_USD,
  CAR_CLASSES_OBJ,
  AMOUNT_LETTERS_OF_ADDRESS,
  KYIV_POSITION,
};
